name: Deploy

on:
  workflow_call:
    inputs:
      service_name:
        type: string
        required: true
      tag_name:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_region:
        required: true
      ecr:
        required: true


jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Docker build and publish
        uses: ./actions/docker-build-and-publish/action.yml
        with:
          image_name: ice-breaker/${{ inputs.service_name }}
          tag_name: ${{ inputs.tag_name }}
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
          aws_region: ${{ secrets.aws_region }}
          ecr: ${{ secrets.ecr }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: build-and-publish
    environment: test
    steps:
      - name: Deploy to test
        uses: ./actions/deploy-ecs/action.yml
        with:
          image: ${{ secrets.ecr }}/ice-breaker/${{ inputs.service_name }}:${{ inputs.tag_name }}
          service_name: ${{ inputs.tag_name }}
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
          aws_region: ${{ secrets.aws_region }}
          ecr: ${{ secrets.ecr }}
