name: Build and Test

on:
  workflow_call:
    inputs:
      ecr:
        required: true
        type: string
      image_name:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      aws_access_key_id:
        required: true
        type: string
      aws_secret_access_key:
        required: true
        type: string
      aws_region:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Docker login
        run: aws ecr get-login-password | docker login --password-stdin --username AWS https://$${{ inputs.ecr }}

      - name: Docker build and tag
        run: docker build -t ${{ inputs.ecr }}/${{ inputs.image_name}}@${{ input.tag_name }} .

      - name: Docker push
        run: docker push ${{ inputs.ecr }}/${{ inputs.image_name}}@${{ input.tag_name }}
